---
- name: Install required packages
  yum: name={{item}} state=latest
  with_items:
    - wget
    - httpd

- name: Download Dispatcher to destination location
  command: "wget -q {{download_url}}"
  args:
    chdir: /etc/httpd/modules
    creates: "{{dispatcher_tar_name}}.tar.gz"
  tags:
    - download_dispatcher

- name: Untar/GZip Dispatcher file
  command: "tar xzf {{dispatcher_tar_name}}.tar.gz"
  args:
    chdir: /opt/
    creates: "{{dispatcher_dir_name}}/"
  tags:
    - untargz_dispatcher